### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gabalafou**
add instructions and screenshot on how to choose a theme from the menu bar

### CODE REVIEW

**Comment by trallard** [comment]
Thanks, @gabalafou - While you are updating the readme, can I ask you to sneak in a doc fix for the issue raised in https://github.com/Quansight-Labs/jupyterlab-accessible-themes/issues/69#issue-1817271413 (only the doc, the rest will be tackled separately)

**Comment by gabalafou** [comment]
If I understand correctly, both the pip and conda commands should use snake-case for this package:

- https://pypi.org/project/jupyterlab-accessible-themes/
- https://anaconda.org/conda-forge/jupyterlab-accessible-themes

**Comment by trallard** [comment]
Yep

**Review by steff456 — APPROVED** [review]
Thanks for updating the readme @gabalafou! This PR looks good to me and ready to merge 🎉

**Pull request merged**
